"""spine

Revision ID: f402f3909114
Revises: 
Create Date: 2026-05-15 02:53:56.239251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f402f3909114'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('store_url', sa.String(length=512), nullable=True),
    sa.Column('critic_score', sa.Float(), nullable=True),
    sa.Column('steam_review_score', sa.Float(), nullable=True),
    sa.Column('steam_review_count', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_igdb_id'), ['igdb_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_steam_appid'), ['steam_appid'], unique=True)

    op.create_table('llm_cache',
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('prompt_hash')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liked_genres', sa.JSON(), nullable=False),
    sa.Column('disliked_genres', sa.JSON(), nullable=False),
    sa.Column('liked_types', sa.JSON(), nullable=False),
    sa.Column('session_length_pref', sa.String(length=16), nullable=False),
    sa.Column('difficulty_pref', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'model_name', name='uq_game_model')
    )
    op.create_table('game_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_tags_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_tags_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_tags_tag'), ['tag'], unique=False)

    op.create_table('library_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('hours_played', sa.Float(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('enjoyment', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('recommendation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_hash', sa.String(length=64), nullable=False),
    sa.Column('filters_applied', sa.JSON(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('abstention_path', sa.String(length=16), nullable=False),
    sa.Column('cluster_label', sa.String(length=64), nullable=True),
    sa.Column('explanation_variant', sa.String(length=16), nullable=False),
    sa.Column('shown_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('started_playing_at', sa.DateTime(), nullable=True),
    sa.Column('dismiss_reason', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_events_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_events_shown_at'), ['shown_at'], unique=False)

    op.create_table('user_game_state',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_state')
    with op.batch_alter_table('recommendation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_events_shown_at'))
        batch_op.drop_index(batch_op.f('ix_recommendation_events_game_id'))

    op.drop_table('recommendation_events')
    op.drop_table('ratings')
    op.drop_table('library_entries')
    with op.batch_alter_table('game_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_tags_tag'))
        batch_op.drop_index(batch_op.f('ix_game_tags_kind'))
        batch_op.drop_index(batch_op.f('ix_game_tags_game_id'))

    op.drop_table('game_tags')
    op.drop_table('game_embeddings')
    op.drop_table('preferences')
    op.drop_table('llm_cache')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_steam_appid'))
        batch_op.drop_index(batch_op.f('ix_games_igdb_id'))

    op.drop_table('games')
    op.drop_table('data_sync_runs')
    # ### end Alembic commands ###
